local options = {
	backup=false,
	clipboard="unnamedplus",
	cmdheight=2,
	completeopt={"menuone", "noselect"},
	conceallevel=0,
	fileencoding="utf-8",
	hlsearch=false,
  incsearch=true,
  termguicolors=true,
	ignorecase=true,
	mouse="a",
	pumheight=10,
	showmode=false,
	showtabline=2,
	smartcase=true,
	smartindent=true,
	splitbelow=true,
	splitright=true,
	swapfile=false,
	timeoutlen=300,
  undodir = "C:/Users/bphil/AppData/Local/nvim/undotree",
	undofile=true,
	updatetime=50,
  colorcolumn="80",
	writebackup=false,
	expandtab=true,
	shiftwidth=2,
	tabstop=2,
  softtabstop=2,
	cursorline=true,
	number=true,
	relativenumber=true,
	numberwidth=2,
	signcolumn="yes",
	wrap=true,
	linebreak=true,
	scrolloff=8,
	sidescrolloff=8,
	guifont="monospace:h17",
	whichwrap="bs<>[]hl",
}

for k,v in pairs(options) do
	vim.opt[k] = v
end
